---
# Codis Version: 3.2, 3.2.11
# 
# FileVersion: 20191113

# Dockerfile
# 


# ####################################
# 环境变量
# ####################################


# ####################################
# 文件映射
# ####################################


version: '3'

services:
  codis-g2-s1:
    image: ${CODIS_IMG_TAG}
    command: codis-server /codis/conf/redis.conf --logfile /codis/log/codis-g2-s1.log
    restart: always
    hostname: codis-g2-s1
    container_name: codis-g2-s1
    ports:
      - ${CODIS_G2_S1_PORT:-16382}:6379
    volumes:
      - ./conf/redis.d/g2-s1.conf:/codis/conf/redis.conf
      - ${XDC_CODIS_DATA:-./data}/codis-g2-s1:/codis/data
      - ${XDC_CODIS_LOG:-./log}:/codis/log
    networks:
      - codis-cluster-g2

  codis-g2-s2:
    image: ${CODIS_IMG_TAG}
    command: codis-server /codis/conf/redis.conf --logfile /codis/log/codis-g2-s2.log
    restart: always
    hostname: codis-g2-s2
    container_name: codis-g2-s2
    ports:
      - ${CODIS_G2_S2_PORT:-16383}:6379
    volumes:
      - ./conf/redis.d/g2-s2.conf:/codis/conf/redis.conf
      - ${XDC_CODIS_DATA:-./data}/codis-g2-s2:/codis/data
      - ${XDC_CODIS_LOG:-./log}:/codis/log
    networks:
      - codis-cluster-g2

  codis-g2-s3:
    image: ${CODIS_IMG_TAG}
    command: codis-server /codis/conf/redis.conf --logfile /codis/log/codis-g2-s3.log
    restart: always
    hostname: codis-g2-s3
    container_name: codis-g2-s3
    ports:
      - ${CODIS_G2_S3_PORT:-16384}:6379
    volumes:
      - ./conf/redis.d/g2-s3.conf:/codis/conf/redis.conf
      - ${XDC_CODIS_DATA:-./data}/codis-g2-s3:/codis/data
      - ${XDC_CODIS_LOG:-./log}:/codis/log
    networks:
      - codis-cluster-g2


networks:
  codis-cluster-g2:
    driver: bridge
