---
# Name: Codis proxy
# Version: 3.2.11 
# FileVersion: 20191113
# Ref: 
#   - https://

# Dockerfile
# 


# ####################################
# 环境变量
# ####################################


# ####################################
# 文件映射
# ####################################


version: '3'

services:
  codis-proxy1:
    image: ${CODIS_IMG_TAG}
    command: codis-proxy -l /codis/log/codis-proxy1.log -c /codis/conf/proxy.toml --host-admin ${CODIS_HOST_NAME}:${CODIS_PROXY_ADMIN_PORT} --host-proxy ${CODIS_HOST_NAME}:${CODIS_PROXY_PORT}
    restart: always
    hostname: codis-proxy1
    container_name: codis-proxy1
    extra_hosts:
      baltic: 172.17.0.1
    ports:
      - ${CODIS_PROXY_ADMIN_PORT}:${PROXY_ADMIN_PORT}
      - ${CODIS_PROXY_PORT}:${PROXY_PORT}
    volumes:
      - ${XDC_CODIS_DATA:-./data}/codis-proxy1:/codis/data
      - ./conf:/codis/conf
      - ${XDC_CODIS_LOG:-./log}:/codis/log
    networks:
      - codis-cluster-proxy


networks:
  codis-cluster-proxy:
    driver: bridge
