---
# Codis Version: 3.2, 3.2.11
# 
# FileVersion: 20191113

# Dockerfile
# 


# ####################################
# 环境变量
# ####################################


# ####################################
# 文件映射
# ####################################


version: '3'

services:
  codis-g4-s1:
    image: ${CODIS_IMG_TAG}
    command: codis-server /codis/conf/redis.conf --logfile /codis/log/codis-g4-s1.log
    restart: always
    hostname: codis-g4-s1
    container_name: codis-g4-s1
    ports:
      - 16388:6379
    volumes:
      - ./data/codis-g4-s1:/codis/data
      - ./conf/redis.d/g4-s1.conf:/codis/conf/redis.conf
      - ../../../log/codis:/codis/log
    networks:
      - codis-cluster-g4

  codis-g4-s2:
    image: ${CODIS_IMG_TAG}
    command: codis-server /codis/conf/redis.conf --logfile /codis/log/codis-g4-s2.log
    restart: always
    hostname: codis-g4-s2
    container_name: codis-g4-s2
    ports:
      - 16389:6379
    volumes:
      - ./data/codis-g4-s2:/codis/data
      - ./conf/redis.d/g4-s2.conf:/codis/conf/redis.conf
      - ../../../log/codis:/codis/log
    networks:
      - codis-cluster-g4

  codis-g4-s3:
    image: ${CODIS_IMG_TAG}
    command: codis-server /codis/conf/redis.conf --logfile /codis/log/codis-g4-s3.log
    restart: always
    hostname: codis-g4-s3
    container_name: codis-g4-s3
    ports:
      - 16390:6379
    volumes:
      - ./data/codis-g4-s3:/codis/data
      - ./conf/redis.d/g4-s3.conf:/codis/conf/redis.conf
      - ../../../log/codis:/codis/log
    networks:
      - codis-cluster-g4


networks:
  codis-cluster-g4:
    driver: bridge
